# Generated by Django 4.2.7 on 2025-12-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_face_encoding_student_face_enrolled_at_and_more'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecognitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(help_text='Version identifier for the model', max_length=50, unique=True)),
                ('model_path', models.CharField(help_text='Path to saved model file', max_length=500)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('dataset_size', models.IntegerField(default=0, help_text='Number of images used for training')),
                ('accuracy', models.FloatField(blank=True, help_text='Model accuracy (0-1)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model version is currently active')),
                ('training_duration_seconds', models.FloatField(blank=True, help_text='Time taken to train the model', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'face_recognition_models',
                'ordering': ['-training_date'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='captured_image',
            field=models.ImageField(blank=True, help_text='Image captured during face recognition', null=True, upload_to='attendance_captures/'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='Confidence score from face recognition (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='face_match_student_id',
            field=models.CharField(blank=True, help_text='Student ID matched by face recognition', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='method',
            field=models.CharField(choices=[('rfid', 'RFID'), ('face', 'Face Recognition'), ('manual', 'Manual')], default='manual', help_text='Method used to record attendance', max_length=10),
        ),
        migrations.CreateModel(
            name='StudentFaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Face image for training', upload_to='student_faces/dataset/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this image is used for training')),
                ('encoding_cached', models.BooleanField(default=False, help_text='Whether face encoding is cached')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_images', to='users.student')),
            ],
            options={
                'db_table': 'student_face_images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
