# Generated by Django 4.2.27 on 2026-01-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_facerecognitionmodel_attendancerecord_captured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfaceimage',
            name='encoding',
            field=models.TextField(blank=True, help_text='JSON representation of 128-d face encoding vector', null=True),
        ),
    ]
