# Generated by Django 4.2.7 on 2025-12-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_encoding',
            field=models.TextField(blank=True, help_text='Stored face encoding (JSON)', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='face_enrolled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='face_image',
            field=models.ImageField(blank=True, help_text='Primary face image for recognition', null=True, upload_to='student_faces/'),
        ),
        migrations.AddField(
            model_name='student',
            name='face_images_count',
            field=models.IntegerField(default=0, help_text='Number of face images in dataset'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_face_enrolled',
            field=models.BooleanField(default=False, help_text='Whether face data is enrolled'),
        ),
    ]
