# Generated by Django 4.2.7 on 2025-12-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='EDURFID', max_length=100)),
                ('site_caption', models.CharField(default='School Sync', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_branding/')),
            ],
        ),
    ]
